cure_dict = {
    "Apple_Apple_scab": "Use fungicide and remove infected leaves.",
    "Apple_Black_rot": "Prune infected branches and apply fungicide.",
    "Apple_Cedar_apple_rust": "Remove nearby cedar trees and use fungicide.",
    "Apple_healthy": "No treatment needed.",
    "Blueberry_healthy": "No treatment needed.",
    "Cherry_(including_sour)_Powdery_mildew": "Use sulfur-based fungicide and ensure good air circulation.",
    "Cherry_(including_sour)_healthy": "No treatment needed.",
    "Corn_(maize)_Cercospora_leaf_spot Gray_leaf_spot": "Use resistant hybrids and apply fungicides.",
    "Corn_(maize)_Common_rust_": "Use resistant varieties and apply fungicides if needed.",
    "Corn_(maize)_Northern_Leaf_Blight": "Apply fungicides and practice crop rotation.",
    "Corn_(maize)_healthy": "No treatment needed.",
    "Grape_Black_rot": "Remove infected leaves and use fungicide during wet weather.",
    "Grape_Esca_(Black_Measles)": "Remove infected wood and avoid pruning in wet conditions.",
    "Grape_Leaf_blight_(Isariopsis_Leaf_Spot)": "Apply fungicides and avoid overhead watering.",
    "Grape_healthy": "No treatment needed.",
    "Orange_Haunglongbing_(Citrus_greening)": "Remove infected trees and control psyllid insects.",
    "Peach_Bacterial_spot": "Use resistant varieties and copper sprays.",
    "Peach_healthy": "No treatment needed.",
    "Pepper,_bell_Bacterial_spot": "Use pathogen-free seeds and copper-based bactericides.",
    "Pepper,_bell_healthy": "No treatment needed.",
    "Potato_Early_blight": "Apply fungicide and rotate crops yearly.",
    "Potato_Late_blight": "Destroy infected plants and apply fungicide regularly.",
    "Potato_healthy": "No treatment needed.",
    "Raspberry_healthy": "No treatment needed.",
    "Soybean_healthy": "No treatment needed.",
    "Squash_Powdery_mildew": "Use fungicides and increase air circulation.",
    "Strawberry_Leaf_scorch": "Remove infected leaves and avoid overhead watering.",
    "Strawberry_healthy": "No treatment needed.",
    "Tomato_Bacterial_spot": "Use copper-based sprays and resistant varieties.",
    "Tomato_Early_blight": "Apply fungicides and remove lower infected leaves.",
    "Tomato_Late_blight": "Apply copper-based fungicide.",
    "Tomato_Leaf_Mold": "Improve ventilation and use fungicide.",
    "Tomato_Septoria_leaf_spot": "Remove infected leaves and apply fungicide.",
    "Tomato_Spider_mites Two-spotted_spider_mite": "Use insecticidal soap or neem oil.",
    "Tomato_Target_Spot": "Apply fungicide and avoid overhead irrigation.",
    "Tomato_Tomato_Yellow_Leaf_Curl_Virus": "Control whiteflies and remove infected plants.",
    "Tomato_Tomato_mosaic_virus": "Remove infected plants and disinfect tools.",
    "Tomato_healthy": "No treatment needed.",
}